### ISSUE TITLE
[Exception] Cannot import channel routing 'example.routing.channel_routing': cannot import name Celery

### ISSUE THREAD

**Issue by cundi** [VincentTide/django-channels-celery-example#1]
I git clone this repository and run it in virtualenv, then I got an error as below. How can I do now?  

```
(.ecommerce-2) ➜  django-channels-celery-example git:(master) python manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x10e601578>
Traceback (most recent call last):
  File "/Users/ml/.ecommerce-2/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/Users/ml/.ecommerce-2/lib/python2.7/site-packages/channels/management/commands/runserver.py", line 38, in inner_run
    self.channel_layer = channel_layers[DEFAULT_CHANNEL_LAYER]
  File "/Users/ml/.ecommerce-2/lib/python2.7/site-packages/channels/asgi.py", line 53, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/Users/ml/.ecommerce-2/lib/python2.7/site-packages/channels/asgi.py", line 48, in make_backend
    routing=routing,
  File "/Users/ml/.ecommerce-2/lib/python2.7/site-packages/channels/asgi.py", line 80, in __init__
    self.router = Router(self.routing)
  File "/Users/ml/.ecommerce-2/lib/python2.7/site-packages/channels/routing.py", line 25, in __init__
    self.root = Include(routing)
  File "/Users/ml/.ecommerce-2/lib/python2.7/site-packages/channels/routing.py", line 200, in __init__
    self.routing = Router.resolve_routing(routing)
  File "/Users/ml/.ecommerce-2/lib/python2.7/site-packages/channels/routing.py", line 74, in resolve_routing
    raise ImproperlyConfigured("Cannot import channel routing %r: %s" % (routing, e))
django.core.exceptions.ImproperlyConfigured: Cannot import channel routing 'example.routing.channel_routing': cannot import name Celery
```

**Comment by VincentTide** [comment]
So I think this is a bug in python 2. Until I figure it out, can you try it with python 3 and see if that works?

**Comment by cundi** [comment]
@VincentTide 
I try to do what you say and it works. 
Many thanks.

```
(.django19) ml@mldeMacBook-Pro ~/D/M/g/django-channels-celery-example> python3 manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
July 29, 2016 - 03:15:06
Django version 1.9.8, using settings 'example.settings'
Starting Channels development server at http://127.0.0.1:8000/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CONTROL-C.
2016-07-29 03:15:06,001 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
2016-07-29 03:15:06,002 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
2016-07-29 03:15:06,003 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
2016-07-29 03:15:06,003 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.receive
[2016/07/29 03:15:07] WebSocket CONNECT /dashboard/ [127.0.0.1:62152]
```
